### ISSUE TITLE
Filter support for weechat listbuffer?

### ISSUE THREAD

**Issue by azizLIGHT** [FiXato/weechat_scripts#4]
I'm not sure if you actively maintain the script anymore but in case you do, could you please add filtering support into ListBuffer? It would make this script as awesome as iset

Thanks

**Comment by azizLIGHT** [comment]
The author doesn't maintain this script anymore because there are better alternatives. I suggest anyone searching to check out server side or web based solutions, as recommended to me by FiXato. For freenode, take a look at alis with /msg alis help.

**Comment by ikwyl6** [comment]
what are the other alternatives?
